SELECT B.PRICE_GROUP, COUNT(B.PRICE_GROUP) AS PRODUCTS
FROM PRODUCT A
JOIN (
    SELECT PRODUCT_ID,
           FLOOR(PRICE/10000)*10000 AS PRICE_GROUP
    FROM PRODUCT
) B
ON A.PRODUCT_ID = B.PRODUCT_ID

GROUP BY B.PRICE_GROUP

ORDER BY PRICE_GROUP ASC;